App/config/routes.rb
Rails.application.routes.draw do
  resources :likes
  post '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/home', to: 'home#display'
  get '/analytics', to: 'home#analytics'
  root :to => 'sessions#welcome'
  
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
  
  resources :tags, only: [:index, :show]

  resources :comments do 
    resources :comment_likes 
  end 

  resources :posts do
    resources :likes, only: [:create, :show, :destroy, :create]
  end

  resources :posts
  
  resources :users

  resources :conversations do
    resources :messages
   end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

App/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :post_tags
    has_many :tags, through: :post_tags
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy

    validates :title, presence: true
    validates :body, presence: true
    accepts_nested_attributes_for :tags, allow_destroy: true, reject_if: :all_blank


    def summary
        self.body[0..1000] + "..."
    end
    #like-related post methods
    def self.like_count_hash
        posts = {}
        Post.all.each do |post|
            posts[post] = post.likes.count
        end
        posts
    end

    def self.ordered_by_likes
        posts = self.like_count_hash
        Hash[posts.sort_by{|k, v| v}.reverse]
    end

    def self.top_ten_posts
        posts = self.ordered_by_likes
        posts.first(10).to_h
    end

    def self.most_popular
        posts = self.ordered_by_likes
        posts.first
    end

    def self.least_popular
        posts = self.ordered_by_likes
        posts.reverse_each.first
    end

    #time-related post methods
    def self.ordered_by_creation
        Post.all.reverse
    end

    def self.newest_ten_posts
        posts = self.ordered_by_creation
        posts.first(10)
    end
    
    def self.newest_post 
        posts = self.ordered_by_creation
        posts.first
    end 

    #comment-related post methods
    def comment_like_count_hash
        comments = {}
        self.comments.each do |comment|
            comments[comment] = comment.comment_likes.count
        end
        comments
    end

    def comments_ordered_by_likes
        comments = self.comment_like_count_hash
        Hash[comments.sort_by{|k, v| v}.reverse]
    end

    def top_ten_post_comments
        comments = self.comments_ordered_by_likes
        comments.first(10).to_h
    end
    
    def top_three_post_comments
        comments = self.comments_ordered_by_likes
        comments.first(3).to_h
    end

    def comments_ordered_by_creation
        self.comments.reverse
    end

    def comments_to_display
        comments_ordered_by_creation.select{|comment| top_three_post_comments.include?(comment) == false}
    end

    def newest_ten_post_comments
        comments = self.comments_ordered_by_creation
        comments.first(10)
    end

    def comment_count
        self.comments.count
    end

    def self.comment_count_hash
        posts = {}
        Post.all.each do |post|
            posts[post] = post.comments.count
        end
        posts
    end

    def self.ordered_by_comments
        posts = self.comment_count_hash
        Hash[posts.sort_by{|k, v| v}.reverse]
    end

    def self.top_ten_most_commented
        posts = self.ordered_by_comments
        posts.first(10).to_h
    end

    def self.most_commented
        self.top_ten_most_commented.first
    end

    def self.least_commented
        self.top_ten_most_commented.reverse_each.first
    end

end

App/app/controllers/home_controller.rb
class HomeController < ApplicationController

    layout 'base'
    before_action :remember_location

    def display
        @current_user = current_user
        @posts = Post.ordered_by_likes.keys
        @tags = Tag.all
        @top_ten_tags = Tag.tag_colors
        @new_post = Post.new
    end

    def analytics

        @current_user = current_user
        @top_ten_tags = Tag.tag_colors

        #User Analytics
        @user_count = User.all.count
        @top_ten_most_active = User.top_ten_users
        @top_ten_most_popular = User.top_ten_most_popular
        @top_ten_likers = User.top_ten_likers

        #Post Analytics
        @post_count = Post.all.count
        @top_ten_posts = Post.top_ten_posts
        @top_ten_most_commented_posts = Post.top_ten_most_commented

        #Comment Analytics
        @comment_count = Comment.all.count
        @top_ten_comments = Comment.top_ten_comments


    end
end

App/app/helpers/home_helper.rb
module HomeHelper
end

App/app/views/home/analytics.html.erb
<%= content_for :navbar do%>
<a href="/home" class="w3-bar-item w3-button w3-padding-large" ><i class="fa fa-home w3-margin-right"></i>Bruhdit</a>
  <a href="/posts" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="All Posts"><i class="fa fa-globe"></i></a>
  <a href="/tags" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="All Tags"><i class="fa fa-tags"></i></a>
  <div class="w3-dropdown-hover w3-hide-small">
  </div>
  <%= button_to("Logout", '/logout',  {method: :post, class: 'w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white'})%>
  <%= link_to(conversations_path, class: "w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white") do %>
      <i class="fa fa-envelope"></i><span class="w3-badge w3-right w3-small w3-green"><%= User.find(session[:user_id]).unread_messages%></span>
  <%end%>
  <%= link_to('/analytics', class: "w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white  w3-theme-d4") do %>
    <i class="fa fa-line-chart"></i>
  <%end%>
<%end%>
<% content_for :page_container do %>
<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:80px">    
  <!-- The Grid -->
  <div class="w3-row">

    <!-- Left Column -->
    <%= render 'layouts/left'%>
    
    
    <!-- Middle Column -->
    <div class="w3-col m7">
     
     <div class="w3-container w3-theme-d1 w3-margin">
        <h1>User Analytics</h1>
      </div>
      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
         <%= content_tag(:h4, "Total # of Users: #{@user_count}", class: "w3-left w3-circle w3-margin-right")%> 
      </div>
      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
         <%= content_tag(:h4, "Top 10 Most Active Users:", class: "w3-left w3-circle w3-margin-right")%> <br>
         <br>
         <ol>
         <%@top_ten_most_active.each_pair do |user, value|%>
            <li><%=user.user_name%></li><ul><li><%="#{value} Total Posts"%></li></ul>
        <%end%>
        </ol>
      </div>
      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
         <%= content_tag(:h4, "Top 10 Most Popular Users:", class: "w3-left w3-circle w3-margin-right")%> <br>
         <br>
         <ol>
         <%@top_ten_most_popular.each_pair do |user, value|%>
            <li><%=user.user_name%></li><ul><li><%="#{value} Total Likes Received"%></li></ul>
        <%end%>
        </ol>
      </div>
      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
         <%= content_tag(:h4, "Top 10 Biggest Likers:", class: "w3-left w3-circle w3-margin-right")%> <br>
         <br>
         <ol>
         <%@top_ten_likers.each_pair do |user, value|%>
            <li><%=user.user_name%></li><ul><li><%="#{value} Total Likes Given"%></li></ul>
        <%end%>
        </ol>
      </div>        

     <div class="w3-container w3-theme-d1 w3-margin">
        <h1>Post Analytics</h1>
      </div>
      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
         <%= content_tag(:h4, "Total # of Posts: #{@post_count}", class: "w3-left w3-circle w3-margin-right")%> 
      </div>
      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
         <%= content_tag(:h4, "Top 10 Most Liked Posts:", class: "w3-left w3-circle w3-margin-right")%> <br>
         <br>
         <ol>
         <%@top_ten_posts.each_pair do |post, value|%>
            <li><%=link_to(post.title, post_path(post))%></li><ul><li><%="#{value} Total Likes Received"%></li></ul>
        <%end%>
        </ol>
      </div>
      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
         <%= content_tag(:h4, "Top 10 Most Commented Posts:", class: "w3-left w3-circle w3-margin-right")%> <br>
         <br>
         <ol>
         <%@top_ten_most_commented_posts.each_pair do |post, value|%>
            <li><%=link_to(post.title, post_path(post))%></li><ul><li><%="#{value} Total Comments"%></li></ul>
        <%end%>
        </ol>
      </div> 

      <div class="w3-container w3-theme-d1 w3-margin">
        <h1>Comment Analytics</h1>
      </div>

      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
         <%= content_tag(:h4, "Total # of Comments: #{@comment_count}", class: "w3-left w3-circle w3-margin-right")%> 
      </div>      

      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
         <%= content_tag(:h4, "Top 10 Most Liked Comments:", class: "w3-left w3-circle w3-margin-right")%> <br>
         <br>
         <ol>
         <%@top_ten_comments.each_pair do |comment, value|%>
            <li><%=link_to(comment.body, post_path(comment.post))%></li><ul><li><%="#{value} Total Likes"%></li></ul>
        <%end%>
        </ol>
      </div> 

    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
<br>
<%end%>

App/app/views/home/display.html.erb
<%= content_for :navbar do%>
<a href="/home" class="w3-bar-item w3-button w3-padding-large w3-theme-d4" ><i class="fa fa-home w3-margin-right"></i>Bruhdit</a>
  <a href="/posts" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="All Posts"><i class="fa fa-globe"></i></a>
  <a href="/tags" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="All Tags"><i class="fa fa-tags"></i></a>
  <div class="w3-dropdown-hover w3-hide-small">
  </div>
  <%= button_to("Logout", '/logout',  {method: :post, class: 'w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white'})%>
  <%= link_to(conversations_path, class: "w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white") do %>
      <i class="fa fa-envelope"></i><span class="w3-badge w3-right w3-small w3-green"><%= User.find(session[:user_id]).unread_messages%></span>
  <%end%>
  <%= link_to('/analytics', class: "w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white") do %>
    <i class="fa fa-line-chart"></i>
  <%end%>
<%end%>

<% content_for :page_container do %>
<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:80px">    
  <!-- The Grid -->
  <div class="w3-row">
   <!-- Left Column -->
    <%= render 'layouts/left'%>
    
    <!-- Middle Column -->
    <div class="w3-col m7">

    
      <div class="w3-container w3-theme-d1 w3-margin">
        <h1>Home Page</h1>
      </div>

      <div class="w3-row-padding">
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div class="w3-container w3-padding">
              <h3 class="w3-opacity">Create a New Post!</h3>
              <%= form_for(@new_post, url: posts_path) do |f|%>
                 <%= f.text_field :title, placeholder: "Your Post's Title!", class: "w3-input w3-border w3-padding"%><br /> 
                 <%= f.text_area :body, placeholder: "Your New Post!", class: "w3-input w3-border w3-padding"%><br />
                 <%= f.collection_check_boxes(:tag_ids, @tags, :id, :name) do |b|%>
                    <%=b.label(:"data-value" => b.value) { b.check_box + b.text}%>
                 <% end%> <br>
                 <h6 class="w3-opacity">Create your own tag!</h6>
                 <%= f.fields_for :tags, @new_post.tags.build do |tag| %>
                    <%= tag.text_field :name, placeholder: "Your New Tag!"%> <br>
                    <br>
                  <%end%>
                  <%= button_tag( class: "w3-button w3-theme") do %>
                    <i class="fa fa-pencil"></i> Post
                  <% end %>
              <%end%>
            </div>
          </div>
        </div>
      </div>

      <%=render 'posts/display'%>
   
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
<br>
<%end%>

App/app/views/home/old.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title>CSS Template</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= stylesheet_link_tag "home" %>

</head>
<body>
<div class = "dropdown" style="float:right;">
  <button class="dropbtn">User Settings</button>
  <div class="dropdown-content">
    <%= link_to("Settings", users_path(session[:user_id]))%>
    <%= link_to("Inbox", users_path(session[:user_id]))%>
    <%= button_to("Logout", '/logout',  {method: :post, class: 'button'})%>
  </div>
</div>
<div class="header">
  <h2>Home</h2>
</div>

<section id = "navbar", class = "wrapper">
    <ul>
      <li> <a href="/home">Home</a> </li>
      <li><a href="/posts">Posts</a> </li>
      <li><a href="/tags">Tags</a> </li>
    <ul>
</section>


<div class="content">
  <h2>Top Posts</h2>
    <div class = "container">
      <% @posts.each do |post|%>
        <div>
          <%= link_to(post.title, post_path(post))%> 
          <%= post.body%>
            <ul>
              <% post.tags.each do |tag|%>
                <li><%= link_to(tag.name, tag_path(tag))%> </li>
              <%end%>
            </ul>
        </div>
      <%end%>
    </div>
</div>

</body>
</html>