App/config/routes.rb
Rails.application.routes.draw do
  resources :likes
  post '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/home', to: 'home#display'
  get '/analytics', to: 'home#analytics'
  root :to => 'sessions#welcome'
  
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
  
  resources :tags, only: [:index, :show]

  resources :comments do 
    resources :comment_likes 
  end 

  resources :posts do
    resources :likes, only: [:create, :show, :destroy, :create]
  end

  resources :posts
  
  resources :users

  resources :conversations do
    resources :messages
   end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

App/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :post_tags
    has_many :tags, through: :post_tags
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy

    validates :title, presence: true
    validates :body, presence: true
    accepts_nested_attributes_for :tags, allow_destroy: true, reject_if: :all_blank


    def summary
        self.body[0..1000] + "..."
    end
    #like-related post methods
    def self.like_count_hash
        posts = {}
        Post.all.each do |post|
            posts[post] = post.likes.count
        end
        posts
    end

    def self.ordered_by_likes
        posts = self.like_count_hash
        Hash[posts.sort_by{|k, v| v}.reverse]
    end

    def self.top_ten_posts
        posts = self.ordered_by_likes
        posts.first(10).to_h
    end

    def self.most_popular
        posts = self.ordered_by_likes
        posts.first
    end

    def self.least_popular
        posts = self.ordered_by_likes
        posts.reverse_each.first
    end

    #time-related post methods
    def self.ordered_by_creation
        Post.all.reverse
    end

    def self.newest_ten_posts
        posts = self.ordered_by_creation
        posts.first(10)
    end
    
    def self.newest_post 
        posts = self.ordered_by_creation
        posts.first
    end 

    #comment-related post methods
    def comment_like_count_hash
        comments = {}
        self.comments.each do |comment|
            comments[comment] = comment.comment_likes.count
        end
        comments
    end

    def comments_ordered_by_likes
        comments = self.comment_like_count_hash
        Hash[comments.sort_by{|k, v| v}.reverse]
    end

    def top_ten_post_comments
        comments = self.comments_ordered_by_likes
        comments.first(10).to_h
    end
    
    def top_three_post_comments
        comments = self.comments_ordered_by_likes
        comments.first(3).to_h
    end

    def comments_ordered_by_creation
        self.comments.reverse
    end

    def comments_to_display
        comments_ordered_by_creation.select{|comment| top_three_post_comments.include?(comment) == false}
    end

    def newest_ten_post_comments
        comments = self.comments_ordered_by_creation
        comments.first(10)
    end

    def comment_count
        self.comments.count
    end

    def self.comment_count_hash
        posts = {}
        Post.all.each do |post|
            posts[post] = post.comments.count
        end
        posts
    end

    def self.ordered_by_comments
        posts = self.comment_count_hash
        Hash[posts.sort_by{|k, v| v}.reverse]
    end

    def self.top_ten_most_commented
        posts = self.ordered_by_comments
        posts.first(10).to_h
    end

    def self.most_commented
        self.top_ten_most_commented.first
    end

    def self.least_commented
        self.top_ten_most_commented.reverse_each.first
    end

end

App/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :current_post, only: [:show, :edit, :update, :destroy]
    before_action :allowed_user, only: [:edit, :update, :destroy]
    before_action :remember_location, only: [:show, :edit]
    layout 'base'
    def index
        @current_user = current_user
        @posts = Post.ordered_by_creation
        @tags = Tag.all
        @top_ten_tags = Tag.tag_colors
        @new_post = Post.new
    end
    
    def new
        @post = Post.new
        @tags = Tag.all
        @user = current_user
    end

    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        validate(home_path)
    end

    def show
        @current_user = current_user
        @comments = @post.comments_to_display
        @top_three_comments = @post.top_three_post_comments.keys
        @top_ten_tags = Tag.tag_colors
        @new_comment = Comment.new()
    end

    def edit
        @tags = Tag.all
        @post = current_post
        @current_user = current_user
        @top_ten_tags = Tag.tag_colors
        @top_three_comments = @post.top_three_post_comments.keys
        @comments = @post.comments_to_display
    end 

    def update 
        @current_user = current_user
        @post.update(post_params)
        validate(edit_post_path)
    end 

    def destroy 
        @post.destroy
        redirect_to '/home'
    end
    
    private

    def current_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:user_id, :title, :body, tag_ids: [], tags_attributes: [:name])
    end

    def validate(error_path)
        if @post.valid?
            @post.save
            redirect_to post_path(@post)
        else
            flash[:errors] = @post.errors.full_messages
            redirect_to error_path
        end
    end

    def allowed_user
        redirect_to post_path(@post) if current_user.id != @post.user.id
    end
end

App/app/helpers/posts_helper.rb
module PostsHelper
end

App/app/views/posts/_comments.html.erb
      <h5 class="w3-opacity">Top Comments</h5>
      <% @top_three_comments.each do |comment|%>
        <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
         <img src=<%=comment.user.image%> alt="Avatar" class="w3-left" style="width:60px">
         <%current_conversation = @current_user.convo_exists?(comment.user)%>
        <%if current_conversation%>
          <%= content_tag(:h6, link_to(comment.user.user_name, conversation_messages_path(current_conversation)), class: "w3-left w3-circle w3-margin-right")%><br />
        <%else%>
          <%= content_tag(:h6, button_to(comment.user.user_name, conversations_path(sender_id: @current_user.id, recipient_id: comment.user.id)), class: "w3-left w3-circle w3-margin-right")%><br/>
          <br>
        <%end%>
        <span class="w3-right w3-opacity"><%= "#{pluralize(comment.comment_likes.count, "Like")}"%></span> <br>
        <span class="w3-right w3-opacity"><%= time_ago_in_words(comment.created_at)+ " ago"%></span>
        <hr class="w3-clear">
        <%= content_tag(:p, comment.body, class: "w3-left")%>
          <br>
          <div class ="w3-row">
                <% pre_like = comment.comment_likes.find { |like| like.user_id == current_user.id} %>
                <% if pre_like %>
                  <%= button_to '❌ Unlike', comment_comment_like_path(comment, pre_like), method: :delete, params: {user_id: @current_user.id, post_id: @post.id}%>
                <% else %>
                  <%= button_to '❤️ Like', comment_comment_likes_path(comment),  method: :post, params: {user_id: @current_user.id, post_id: @post.id} %>
                <% end %>    
                <%if @current_user.id == comment.user_id%>
                  <%= button_to "Edit Comment", edit_comment_path(comment), method: :get, params: {user_id: @current_user.id, post_id: @post.id}%>
                  <%= button_to"Delete Comment", comment_path(comment), method: :delete, params: {user_id: @current_user.id, post_id: @post.id}%>
                <%end%>
        </div>
      </div>
      <%end%>

      <h5 class="w3-opacity">All Comments</h5>
      <% @comments.each do |comment|%>
        <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
         <img src=<%=comment.user.image%> alt="Avatar" class="w3-left" style="width:60px">
         <%current_conversation = @current_user.convo_exists?(comment.user)%>
        <%if current_conversation%>
          <%= content_tag(:h6, link_to(comment.user.user_name, conversation_messages_path(current_conversation)), class: "w3-left w3-circle w3-margin-right")%><br />
        <%else%>
          <%= content_tag(:h6, button_to(comment.user.user_name, conversations_path(sender_id: @current_user.id, recipient_id: comment.user.id)), class: "w3-left w3-circle w3-margin-right")%><br/>
          <br>
        <%end%>
        <span class="w3-right w3-opacity"><%= "#{pluralize(comment.comment_likes.count, "Like")}"%></span> <br>
        <span class="w3-right w3-opacity"><%= time_ago_in_words(comment.created_at)+ " ago"%></span>
        <hr class="w3-clear">
        <%= content_tag(:p, comment.body, class: "w3-left")%>
          <br>
          <div class ="w3-row">
                <% pre_like = comment.comment_likes.find { |like| like.user_id == current_user.id} %>
                <% if pre_like %>
                  <%= button_to '❌ Unlike', comment_comment_like_path(comment, pre_like), method: :delete, params: {user_id: @current_user.id, post_id: @post.id}%>
                <% else %>
                  <%= button_to '❤️ Like', comment_comment_likes_path(comment),  method: :post, params: {user_id: @current_user.id, post_id: @post.id} %>
                <% end %>    
                <%if @current_user.id == comment.user_id%>
                  <%= button_to "Edit Comment", edit_comment_path(comment), method: :get, params: {user_id: @current_user.id, post_id: @post.id}%>
                  <%= button_to"Delete Comment", comment_path(comment), method: :delete, params: {user_id: @current_user.id, post_id: @post.id}%>
                <%end%>
        </div>
      </div>
      <%end%>
      

App/app/views/posts/_current.html.erb
<%= content_for :navbar do%>
<a href="/home" class="w3-bar-item w3-button w3-padding-large" ><i class="fa fa-home w3-margin-right"></i>Bruhdit</a>
  <a href="/posts" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="All Posts"><i class="fa fa-globe"></i></a>
  <a href="/tags" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="All Tags"><i class="fa fa-tags"></i></a>
  <div class="w3-dropdown-hover w3-hide-small">
  </div>
  <%= button_to("Logout", '/logout',  {method: :post, class: 'w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white'})%>
  <%= link_to(conversations_path, class: "w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white") do %>
      <i class="fa fa-envelope"></i><span class="w3-badge w3-right w3-small w3-green"><%= User.find(session[:user_id]).unread_messages%></span>
  <%end%>
  <%= link_to('/analytics', class: "w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white") do %>
    <i class="fa fa-line-chart"></i>
  <%end%>
<%end%>

<% content_for :page_container do %>
<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:80px; margin-bottom:170px">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <%=render 'posts/left'%>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
        <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
         <%= content_tag(:h4, @post.title, class: "w3-left w3-circle w3-margin-right")%>
        <span class="w3-right w3-opacity"><%= "#{pluralize(@post.likes.count, "Like")}"%></span> <br>
        <span class="w3-right w3-opacity"><%= "#{pluralize(@post.comments.count, "Comment")}"%></span> <br>
        <span class="w3-right w3-opacity"><%= time_ago_in_words(@post.created_at)+ " ago"%></span>
        <hr class="w3-clear">
        <img src=<%=@post.user.image%> alt="Avatar" class="w3-left" style="width:60px">
        <%= content_tag(:p, @post.body, class: "w3-left")%>
          <div class="w3-row-padding" style="margin:0 -16px">
            <div class ="w3-row">
              Tags:
              <%@post.tags.each do |tag| %>
                  <span class="w3-tag w3-small w3-theme-d1"><%=link_to(tag.name, tag_path(tag))%></span>
              <%end%> 
            </div>
          </div>
          <br>
          <div class ="w3-row">

                <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
                <% if pre_like %>
                  <%= button_to '❌ Unlike', post_like_path(@post, pre_like), method: :delete %>
                <% else %>
                  <%= button_to '❤️ Like', post_likes_path(@post), { method: :post} %>
                <% end %> <br>
                
      </div>
      </div>
      <div class="w3-row-padding">
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div class="w3-container w3-padding">
              <h6 class="w3-opacity">Edit Comment</h6>
              <%= form_for @comment do |f|%>
                <%= f.hidden_field :post_id, value: @post.id %>
                <%= f.hidden_field :user_id, value: @current_user.id %>
                 <%= f.text_area :body, placeholder: "Your New Comment!", class: "w3-input w3-border w3-padding"%><br />
                  <%= button_tag( class: "w3-button w3-theme") do %>
                    <i class="fa fa-pencil"></i> Update
                  <% end %>
              <%end%>
            </div>
          </div>
        </div>
      </div>

      <%=render 'posts/comments'%>

      
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
<br>

<%end%>

App/app/views/posts/_display.html.erb
<% @posts.each do |post|%>
        <div class="w3-container w3-card w3-white w3-round w3-margin"><br>

         <img src=<%=post.user.image%> alt="Avatar" class="w3-left" style="width:60px">
        <%current_conversation = @current_user.convo_exists?(post.user)%>
        <%if current_conversation%>
          <%= content_tag(:h6, link_to(post.user.user_name, conversation_messages_path(current_conversation)), class: "w3-left w3-hover w3-circle w3-margin-right")%><br />
        <%else%>
          <%= content_tag(:h6, button_to(post.user.user_name, conversations_path(sender_id: @current_user.id, recipient_id: post.user.id)), class: "w3-left w3-hover w3-circle w3-margin-right")%><br/>
        
        <%end%>
        <span class="w3-right w3-opacity"><%= "#{pluralize(post.likes.count, "Like")}"%></span> <br>
        <span class="w3-right w3-opacity"><%= time_ago_in_words(post.created_at)+ " ago"%></span>
        <hr class="w3-clear">
        <%= content_tag(:h4, link_to(post.title, post_path(post)), class: "w3-left w3-circle w3-margin-right")%><br />
        <br>
        <br>
        <%= content_tag(:p, post.summary, class: "w3-left")%>
          <div class="w3-row-padding" style="margin:0 -16px">
            <div class ="w3-row">
              Tags:
              <%post.tags.each do |tag| %>
                  <span class="w3-tag w3-small w3-theme-d1"><%=link_to(tag.name, tag_path(tag))%></span>
              <%end%> 
            </div>
          </div>
          <br>
          <div class ="w3-row">
                <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
                <% if pre_like %>
                  <%= button_to '❌ Unlike', post_like_path(post, pre_like), method: :delete %>
                <% else %>
                  <%= button_to '❤️ Like', post_likes_path(post), { method: :post} %>
                <% end %>         
                <%= button_to(post_path(post), method: :get, class: "w3-button w3-theme-d2 w3-margin-bottom") do %>
                  <i class="fa fa-comment"></i> Leave a Comment
                <% end %>
        </div>
      </div>
      <%end%>

App/app/views/posts/_form.html.erb
<%=render 'layouts/flash'%>

<%= content_for :navbar do%>
<a href="/home" class="w3-bar-item w3-button w3-padding-large" ><i class="fa fa-home w3-margin-right"></i>Bruhdit</a>
  <a href="/posts" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="All Posts"><i class="fa fa-globe"></i></a>
  <a href="/tags" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="All Tags"><i class="fa fa-tags"></i></a>
  <div class="w3-dropdown-hover w3-hide-small">
  </div>
  <%= button_to("Logout", '/logout',  {method: :post, class: 'w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white'})%>
  <%= link_to(conversations_path, class: "w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white") do %>
      <i class="fa fa-envelope"></i><span class="w3-badge w3-right w3-small w3-green"><%= User.find(session[:user_id]).unread_messages%></span>
  <%end%>
  <%= link_to('/analytics', class: "w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white") do %>
    <i class="fa fa-line-chart"></i>
  <%end%>
<%end%>

<% content_for :page_container do %>
<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:80px; margin-bottom:170px">    
  <!-- The Grid -->
  <div class="w3-row">
  
   <%= render 'left'%>

    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding">
              <div class="w3-col m12">
                <div class="w3-card w3-round w3-white">
                  <div class="w3-container w3-padding">
                    <h6 class="w3-opacity">Edit your Post!</h6>
                    <%= form_for(@post) do |f|%>
                      <%= f.text_field :title, placeholder: "Your Post's Title!", class: "w3-input w3-border w3-padding"%><br /> 
                      <%= f.text_area :body, placeholder: "Your New Post!", class: "w3-input w3-border w3-padding"%><br />
                      <%= f.collection_check_boxes(:tag_ids, @tags, :id, :name) do |b|%>
                          <%=b.label(:"data-value" => b.value) { b.check_box + b.text}%>
                      <% end%> <br>
                      <%= f.fields_for :tags, @post.tags.build do |tag| %>
                          <%= tag.text_field :name %> <br>
                        <%end%>
                        <%= button_tag( class: "w3-button w3-theme") do %>
                          <i class="fa fa-pencil"></i> Post
                        <% end %>
                    <%end%>

                    <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
                    <% if pre_like %>
                      <%= button_to '❌ Unlike', post_like_path(@post, pre_like), method: :delete %>
                    <% else %>
                      <%= button_to '❤️ Like', post_likes_path(@post), { method: :post} %>
                    <% end %> <br>
                    <%if @current_user.id == @post.user_id%>
                      <%= button_to "Delete Post", post_path(@post), method: :delete, params: {user_id: @current_user.id, post_id: @post.id}%>
                    <% end %>

                  </div>
                </div>
              </div>
            </div>


          <br>
          <div class ="w3-row">         

      <%=render 'comments'%>

      
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
<br>

<%end%>

App/app/views/posts/_left.html.erb
  <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
         <h4 class="w3-center"><%= "#{@post.user.user_name}'s Profile"%></h4>
         <p class="w3-center"><img src=<%=@post.user.image%> class="w3-circle" style="height:106px;width:106px" alt="Avatar"></p>
         <hr>
         <%current_conversation = @current_user.convo_exists?(@post.user)%>
        <%if current_conversation%>
          <%= content_tag(:h6, link_to(" Chat with #{@post.user.user_name}!", conversation_messages_path(current_conversation)), class: "w3-center w3-circle w3-margin-right")%><br />
        <%else%>
          <%= content_tag(:h6, button_to("Chat with #{@post.user.user_name}!", conversations_path(sender_id: @current_user.id, recipient_id: @post.user.id)), class: "w3-center w3-circle w3-margin-right")%><br/>
          <br>
        <%end%>
        </div>
      </div>
      <br>
    
     <!-- Interests --> 
      <div class="w3-card w3-round w3-white w3-hide-small">
        <div class="w3-container">
          <p>Top 10 Tags</p>
          <p>
            <% @top_ten_tags.each do |tag, color|%>
              <%= content_tag(:span, link_to(tag.name.titleize, tag_path(tag)), class: color)%>
            <%end%>
          </p>
        </div>
      </div>
      <br>
    
    <!-- End Left Column -->
    </div>
    

App/app/views/posts/edit.html.erb
<%= render 'form' %>

App/app/views/posts/new.html.erb
<%= render 'form' %>

App/app/views/posts/old_show.html.erb
<h1><%=@post.title%></h1>
<h3>By: <%=@post.user.user_name%></h3>
<p><%=@post.body%></p>

<h3>Post tags</h3>

<% @post.tags.each {|tag| %>
    <p><%=tag.name%></p>
<% } %>

<p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
<% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <%= button_to 'Unlike ❌', post_like_path(@post, pre_like), method: :delete %>
<% else %>
  <%= button_to 'Like ❤️', post_likes_path(@post), method: :post %>
<% end %>

<%if @current_user.id == @post.user_id%>
    <%= button_to "Edit Post", edit_post_path(@post), method: :get%>
    <%= button_to "Delete Post", post_path(@post), method: :delete%>
<%end%>

<h3>Comments</h3>
<%= button_to "Add a Comment", {controller: "comments", action: "new"}, method: :get, params: {user_id: @current_user.id, post_id: @post.id}%>
<% @comments.each {|comment| %>
    <p><%=comment.user.user_name%></p>
    <p><%=comment.body%></p>
    <p><%= comment.comment_likes.count %> <%= (comment.comment_likes.count) == 1 ? 'Like' : 'Likes'%></p>
    <% pre_like = comment.comment_likes.find { |like| like.user_id == current_user.id} %>
    <% if pre_like %>
      <%= button_to 'Unlike ❌', comment_comment_like_path(comment, pre_like), method: :delete, params: {user_id: @current_user.id, post_id: @post.id} %>
    <% else %>
      <%= button_to 'Like ❤️', comment_comment_likes_path(comment), method: :post, params: {user_id: @current_user.id, post_id: @post.id} %>
    <% end %>
    <%if @current_user.id == comment.user_id%>
    <%= button_to "Edit Comment", edit_comment_path(comment), method: :get, params: {user_id: @current_user.id, post_id: @post.id}%>
    <%= button_to"Delete Comment", comment_path(comment), method: :delete, params: {user_id: @current_user.id, post_id: @post.id}%>
<%end%>
<% } %>

App/app/views/posts/show.html.erb
<%= content_for :navbar do%>
<a href="/home" class="w3-bar-item w3-button w3-padding-large" ><i class="fa fa-home w3-margin-right"></i>Bruhdit</a>
  <a href="/posts" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="All Posts"><i class="fa fa-globe"></i></a>
  <a href="/tags" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="All Tags"><i class="fa fa-tags"></i></a>
  <div class="w3-dropdown-hover w3-hide-small">
  </div>
  <%= button_to("Logout", '/logout',  {method: :post, class: 'w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white'})%>
  <%= link_to(conversations_path, class: "w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white") do %>
      <i class="fa fa-envelope"></i><span class="w3-badge w3-right w3-small w3-green"><%= User.find(session[:user_id]).unread_messages%></span>
  <%end%>
  <%= link_to('/analytics', class: "w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white") do %>
    <i class="fa fa-line-chart"></i>
  <%end%>
<%end%>

<% content_for :page_container do %>
<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:80px; margin-bottom:170px">    
  <!-- The Grid -->
  <div class="w3-row">
  <%=render 'left'%>

    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
        <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
         <%= content_tag(:h2, @post.title, class: "w3-left w3-circle w3-margin-right")%>
        <span class="w3-right w3-opacity"><%= "#{pluralize(@post.likes.count, "Like")}"%></span> <br>
        <span class="w3-right w3-opacity"><%= "#{pluralize(@post.comments.count, "Comment")}"%></span> <br>
        <span class="w3-right w3-opacity"><%= time_ago_in_words(@post.created_at)+ " ago"%></span>
        <hr class="w3-clear">
        <%= content_tag(:h4, @post.body, class: "w3-left")%>
          <div class="w3-row-padding" style="margin:0 -16px">
            <div class ="w3-row">
              Tags:
              <%@post.tags.each do |tag| %>
                  <span class="w3-tag w3-small w3-theme-d1"><%=link_to(tag.name, tag_path(tag))%></span>
              <%end%> 
            </div>
          </div>
          <br>
          <div class ="w3-row">

                <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
                <% if pre_like %>
                  <%= button_to '❌ Unlike', post_like_path(@post, pre_like), method: :delete %>
                <% else %>
                  <%= button_to '❤️ Like', post_likes_path(@post), { method: :post} %>
                <% end %> <br>
                <%if @current_user.id == @post.user_id%>
                <%= button_to "Edit Post", edit_post_path(@post), method: :get, params: {user_id: @current_user.id, post_id: @post.id}%>
                <%= button_to "Delete Post", post_path(@post), method: :delete, params: {user_id: @current_user.id, post_id: @post.id}%>
                <% end %>
                
      </div>
      </div>
      <div class="w3-row-padding">
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div class="w3-container w3-padding">
              <h6 class="w3-opacity">Add a Comment</h6>
              <%= form_for(@new_comment, url: comments_path)do |f|%>
                <%= f.hidden_field :post_id, value: @post.id %>
                <%= f.hidden_field :user_id, value: @current_user.id %>
                 <%= f.text_area :body, placeholder: "Your New Comment!", class: "w3-input w3-border w3-padding"%><br />
                  <%= button_tag( class: "w3-button w3-theme") do %>
                    <i class="fa fa-pencil"></i> Post
                  <% end %>
              <%end%>
            </div>
          </div>
        </div>
      </div>

      <%=render 'comments'%>
      
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
<br>

<%end%>